export default (http) => {
  // 请求拦截
  http.interceptors.request.use(
    config => {
      // config.withCredentials = true // 需要跨域打开此配置
      // 所有请求登录后带上 access_token
      // if (window.localStorage.hasOwnProperty('token')) {
      //   config.headers.Authorization='Bearer ' + window.localStorage.getItem('token')
      // }
      return config
    },
    error => {
      return Promise.reject(error)
    }
  )
  // https://github.com/mzabriskie/axios#interceptors
  http.interceptors.response.use(
    response => {
      return response.data
    },
    /**
    * This is a central point to handle all
    * error messages generated by HTTP
    * requests
    */
    (error) => {
      return Promise.reject(error)
    }
  )
}
